global.bullets = {};
nu bullet("small", s_bulletsmall, 1, true, false, true, 1);
nu bullet("point", s_bulletpoint, 1, true, false, true, 1);
nu bullet("square", s_bulletsquare, 1, true, false, true, 1);
nu bullet("circle", s_bulletcircle, 1, true, false, true, 1);
nu bullet("bullet", s_bulletbullet, 1, true, false, true, 1);
nu bullet("core", s_bulcore, 1, true, false, true, 1);
nu bullet("card", s_bulcard, 1, true, false, true, 1);
nu bullet("cross", s_bulcross, 1, true, false, true, 1);
nu bullet("thin", s_bulthin, 1, true, false, true, 1);
nu bullet("big", s_bulbig, 1, true, false, true, 1);
nu bullet("star", s_bulstar, 1, true, false, true, 1, u, false);