global.bullets = {};
nu bullet("small", s_bulletsmall, 3, true, false, true, 1);
nu bullet("point", s_bulletpoint, 3, true, false, true, 1);
nu bullet("square", s_bulletsquare, 3, true, false, true, 1);
nu bullet("circle", s_bulletcircle, 3, true, false, true, 1);
nu bullet("bullet", s_bulletbullet, 3, true, false, true, 1);
nu bullet("core", s_bulcore, 3, true, false, true, 1);
nu bullet("card", s_bulcard, 3, true, false, true, 1);
nu bullet("cross", s_bulcross, 3, true, false, true, 1);
nu bullet("thin", s_bulthin, 3, true, false, true, 1);
nu bullet("big", s_bulbig, 3, true, false, true, 1);
nu bullet("star", s_bulstar, 3, true, false, true, 1, u, false);